nationalparks/my_app/urls.py
from django.urls import path
from . import views 

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('about/', views.about, name='about'),
    path('parks/', views.park_index, name='park-index'),
    path('parks/<int:park_id>', views.park_detail, name='park-detail'),
    path('parks/create/', views.ParkCreate.as_view(), name='park-create'),
    path('parks/<int:pk>/update/', views.ParkUpdate.as_view(), name='park-update'),
    path('parks/<int:pk>/delete/', views.ParkDelete.as_view(), name='park-delete'),
    path('parks/<int:park_id>/add-trail/', views.add_trail, name='add-trail'),
    path('accounts/signup/', views.signup, name='signup'),
    path('trails/<int:pk>/update/', views.TrailUpdate.as_view(), name='trail-update'),
    path('trails/<int:pk>/delete/', views.TrailDelete.as_view(), name='trail-delete'),
    
    path('trails/', views.TrailList.as_view(), name='trail-index')

    # path('trails/<int:pk>/', views.TrailDetail.as_view(), name='trail-detail'),
 
]

nationalparks/nationalparks/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

nationalparks/my_app/models.py
from django.db import models
from django.urls import reverse

from django.contrib.auth.models import User


DIFFICULTY = (
    ('E', 'Easy'),
    ('M', 'Moderate'),
    ('D', 'Difficult')
)

# Create your models here.
class NationalPark(models.Model):
    name = models.CharField(max_length=255)
    location = models.CharField(max_length=255) 
    description = models.TextField()
    established_date = models.DateField() 

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('park-detail', kwargs={'park_id': self.id})

    user = models.ForeignKey(User, on_delete=models.CASCADE)



class Trail(models.Model):
    name = models.CharField(max_length=255)
    difficulty = models.CharField(
        max_length=1,
        choices = DIFFICULTY, 
        default = DIFFICULTY[0][0]
        )

    # description = models.CharField(max_length=255)

    national_park = models.ForeignKey(NationalPark, on_delete=models.CASCADE)


    def __str__(self):
        return f"{self.get_difficulty_display()} on {self.name}"

    def get_absolute_url(self):
        return reverse('trail-detail', kwargs={'trail_id': self.id})

    class Meta:
        ordering = ['-name']  
        

nationalparks/my_app/forms.py
from django import forms
from .models import Trail


class TrailForm(forms.ModelForm):
    class Meta:
        model = Trail
        fields = ['name', 'difficulty']
 



        
        

nationalparks/my_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import NationalPark
from .forms import TrailForm
from .models import Trail


from django.http import HttpResponse

# Define the home view function
def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('park-index')
        else:
             error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'signup.html', context)

class Home(LoginView):
    template_name = 'home.html'
    
def about(request):
    return render(request, 'about.html')

@login_required
def park_index(request):
    parks = NationalPark.objects.filter(user=request.user)
    return render(request, 'parks/index.html', {'parks': parks})

@login_required
def park_detail(request, park_id):
    park = NationalPark.objects.get(id=park_id)
    trail_form = TrailForm()
    return render(request, 'parks/detail.html', {'park': park, 'trail_form': trail_form})

@login_required
def add_trail(request, park_id):
    form = TrailForm(request.POST)
    if form.is_valid():
        new_trail = form.save(commit=False)
        new_trail.national_park_id = park_id
        new_trail.save()
    return redirect('park-detail', park_id=park_id)


class ParkCreate(LoginRequiredMixin, CreateView):
    model = NationalPark
    fields = ['name', 'location', 'description', 'established_date']
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    success_url = '/parks/'

# class TrailList(ListView):
#     model = Trail

class TrailDetail(DetailView):
    model = Trail

class ParkUpdate(UpdateView):   
    model = NationalPark
    fields = ['location', 'description', 'established_date']

class ParkDelete(DeleteView):
    model = NationalPark
    success_url = '/parks/'



class TrailUpdate(LoginRequiredMixin, UpdateView):
    model = Trail
    fields = ['name', 'difficulty']
    success_url = '/trails/' 

class TrailDelete(LoginRequiredMixin, DeleteView):
    model = Trail
    success_url = '/trails/' 

class TrailList(ListView):
    model = Trail
    template_name = 'trails/trail_list.html'  
    context_object_name = 'trails'  

nationalparks/my_app/templates/about.html
{% extends 'base.html' %} 

{% block content %}
<h1>National Parks</h1>
<hr />
<p class="page-content">
    Create lasting memories in breathtaking natural landscapes.
    National parks are the ultimate travel destination
</p>
{% endblock %}

nationalparks/my_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" type="image/png" href="" />
    <title>National Parks</title>
    {% block head %} 
    
    {% endblock %}
  </head>
  <body>
    <header>
      <div class="header-logo-container">
        <a href="/">
        </a>
      </div>
      <nav>
        <ul>
          {% if user.is_authenticated %}
            <li><a href="{% url 'park-index' %}">All Parks</a></li>
            <li><a href="{% url 'park-create' %}">Add a Park</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
            <li>
              <form id="logout-form" method="post" action="{% url 'logout' %}">
                {% csrf_token %}
                <button type="submit">Log out</button>
              </form>
            </li>
          {% else %}
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'home' %}">Login</a></li>
          <li><a href="{% url 'signup' %}">Sign Up</a></li>
          {% endif %}
        </ul>
      </nav>      
    </header>
    <main>
     {% block content %} 
     
     {% endblock %}
    </main>
  </body>
</html>

nationalparks/my_app/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/home.css' %}" />
{% endblock %}
{% block content %}

<section class="logo-container">
    <div class="nationalpark-container">
    </div>
  </section>
{% if not user.is_authenticated %} 
  <section>
    <form action="{% url 'home' %}" method="post" class="login">
      <h1>Login</h1>
      {% csrf_token %} {{ form.as_p }}
      <input type="hidden" name="next" value="{{ next }}" />
      <button type="submit" class="btn submit">Login</button>
    </form>
    {% endif %}
</section>
{% endblock %}

nationalparks/my_app/templates/my_app/nationalpark_confirm_delete.html
{% extends 'base.html' %}  
{% load static %} 
{% block content %}

<div class="page-header">
  <h1>Delete Park?</h1>
</div>

<h2>Are you sure you want to delete {{ park.name }}?</h2>

<form action="" method="post" class="form">
  {% csrf_token %}
  <a href="{% url 'park-detail' nationalpark.id %}" class="btn secondary">Cancel</a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

nationalparks/my_app/templates/my_app/nationalpark_form.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}

<div class="page-header">
  <h1>Add a Park</h1>
</div>

<form action="" method="post" class="form-container">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

nationalparks/my_app/templates/my_app/trail_confirm_delete.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}

<div>
  <h1>Delete Trail</h1>
</div>
<form action="" method="post" class="form">
  {% csrf_token %}
  <a href="{% url 'trail-delete' trail.id %}"> Cancel </a>
  <button type="submit" >Delete Trail!</button>
</form>

{% endblock %}

nationalparks/my_app/templates/my_app/trail_form.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}
  <div>
    {% if object %}
      <h1>Edit Trail</h1>
    {% else %}
      <h1>Add a Trail</h1>
    {% endif %}
  </div>
  <form action="" method="post" autocomplete="off">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit" >Submit!</button>
  </form>

{% endblock %}

nationalparks/my_app/templates/my_app/trail_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Trails</h1>
  <ul>
    {% for trail in trails %}
      <li>{{ trail.name }} - {{ trail.get_difficulty_display }}</li>
    {% endfor %}
  </ul>
{% endblock %}

nationalparks/my_app/templates/parks/detail.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/national-parks/park-index.css' %}"/>
{% endblock %}

{% block content %}
<section class="page-header">
  <h1>National Parks</h1>
  <!-- <img src="{% static 'images/national-parks-banner.jpg' %}" alt="National Parks Banner" /> -->
</section>

<section class="card-container">
  <!-- <h2>Explore Our National Parks</h2> -->
    <div class="card">
        <div class="card-content">
          <div class="card-img-container">
            <!-- <img src="{% static 'images/park-placeholder.jpg' %}" alt="{{ park.name }} National Park" /> -->
          </div>
          <h2 class="card-title">{{ park.name }}</h2>
          <p><strong>Location:</strong> {{ park.location }}</p>
          <p><strong>Description:</strong> {{ park.description | truncatechars:150 }}</small></p>  </div>
          <p><strong>Established Date:</strong> {{ park.established_date }}</p>

          <div class="park-actions">
            <a href="{% url 'park-update' park.id %}" class="btn warn">Edit</a>
            <a href="{% url 'park-delete' park.id %}" class="btn danger">Delete</a>
          </div>
        </div>
      </a>
    </div>
</section>

<!-- New index for 2nd model-->
<div class="trails-container">
  <section class="trails">
    <div class="subsection-title">
      <h2>Trails</h2>
    </div>

    <!-- Form for Adding a trail -->
<h3>Add a Trail</h3>
<form 
action="{% url 'add-trail' park.id %}"
method="post"
class="subsection-content" 
autocomplete="off"
>
  {% csrf_token %} 
  {{ trail_form.as_p }}
  <button type="submit" class="btn submit">Add Trail</button>
</form>
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Difficulty</th>
        </tr>
      </thead>
      <tbody>
        {% for trail in park.trail_set.all %}
          <tr>
            <td>{{trail.name}}</td>
            <td>{{trail.get_difficulty_display}}</td>
            <!-- <a href="" class="btn warn">Edit</a>
            <a href="" class="btn danger">Delete</a> -->
            <td><a href="{% url 'trail-update' trail.id %}" > Edit </a></td>
            <td><a href="{% url 'trail-delete' trail.id %}" > Delete </a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </section>
</div>

{% endblock %}

nationalparks/my_app/templates/parks/index.html
{% extends 'base.html' %}
{% load static %}
{% block head %}

<link rel="stylesheet" href="{% static 'css/national-parks/park-index.css' %}"/>
{% endblock %}

{% block content %}
<section class="page-header">
  <h1>National Parks</h1>
  <!-- <img src="{% static 'images/national-parks-banner.jpg' %}" alt="National Parks Banner" /> -->
</section>

<section class="card-container">
  {% for park in parks %}
    <div class="card">
        <div class="card-content">
          <div class="card-img-container">
            <!-- <img src="{% static 'images/park-placeholder.jpg' %}" alt="{{ park.name }} National Park" /> -->
          </div>

          <h2 class="card-title">{{ park.name }} </h2>
            <!-- id:{{park.id}}</h2> -->
              <a href="/parks/{{park.id}}">Visit Park</a>
          <!-- <p><strong>Location:</strong> {{ park.location }}</p>

          <p><strong>Description:</strong> {{ park.description | truncatechars:150 }}</small></p>  </div>

          <p><strong>Established Date:</strong> {{ park.established_date }}</p> -->

      </a>
    </div>
    
  {% endfor %}
</section>
{% endblock %}

nationalparks/my_app/templates/signup.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}
<div class="page-header">
  <h1>Sign Up</h1>
</div>
{% if error_message %}
  <p class="red-text">{{ error_message }}</p>
{% endif %}
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}